aliases:
    fleeks: cd ~/.local/share/fleek
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - atuin
    - rustup
    - nodejs
    - nerdfonts
    - tree
    - distrobox
    - python39
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: aarch64
      hostname: yanns-MacBook-Pro.local
      os: darwin
      username: yann
track: ""
unfree: true
users:
    - email: yann.leguilly@gmail.com
      name: Yann
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: yann
